<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.12.7" />
	<PackageReference Include="DotNetEnv" Version="3.2.0" />
	<PackageReference Include="MediatR" Version="14.0.0" />
	<PackageReference Include="YoomoneyApi" Version="1.0.6" />
	<PackageReference Include="MassTransit.RabbitMQ" Version="9.2.0-develop.154" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchedulerTelegramBot.Contracts\SchedulerTelegramBot.Contracts.csproj" />
  </ItemGroup>

</Project>
