<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>f92104af-a44d-43dd-bff5-6a8a4473e9a8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Bot\Handlers\InlineQueryHandlers\**" />
    <EmbeddedResource Remove="Bot\Handlers\InlineQueryHandlers\**" />
    <None Remove="Bot\Handlers\InlineQueryHandlers\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="DotNetEnv" Version="3.2.0" />
		<PackageReference Include="MassTransit.EntityFrameworkCore" Version="9.2.0-develop.154" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="9.2.0-develop.154" />
		<PackageReference Include="MediatR" Version="14.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.5" />
		<PackageReference Include="Quartz.Extensions.Hosting" Version="3.15.1" />
		<PackageReference Include="Telegrator" Version="1.15.9" />
		<PackageReference Include="Telegrator.Hosting" Version="1.15.9" />
		<PackageReference Include="Telegrator.Hosting.Web" Version="1.15.9" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Extensions\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SchedulerTelegramBot.Contracts\SchedulerTelegramBot.Contracts.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update=".env">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update=".env.local">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
